name: attendance_app
description: "Employee Attendance & Leave Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  provider: ^6.1.5
  intl: ^0.20.2
  geolocator: ^13.0.2
  file_picker: ^8.1.7
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  share_plus: ^10.1.2
  table_calendar: ^3.2.0
  pdf: ^3.11.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: lib/assets/app_icon.png
  web:
    generate: true
    image_path: lib/assets/app_icon.png
    background_color: "#1E3A8A"
    theme_color: "#1A56DB"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo-CEO.png
    - lib/assets/app_icon.png
